// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://impbuojchyyjohedanzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltcGJ1b2pjaHl5am9oZWRhbnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTIxNTAsImV4cCI6MjA3MTE2ODE1MH0.3oJOMcqU8hiCZYAmVp3FqOjThNiVCuB3JjO3NK7k6mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});